// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using appWebEnvio.Data;

#nullable disable

namespace appWebEnvio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219175624_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("appWebEnvio.Models.Clientes", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("appWebEnvio.Models.Destinatarios", b =>
                {
                    b.Property<int>("DestinatarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinatarioId"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinatarioId");

                    b.ToTable("Destinatarios");
                });

            modelBuilder.Entity("appWebEnvio.Models.Envios", b =>
                {
                    b.Property<int>("EnvioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnvioId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.HasKey("EnvioId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("appWebEnvio.Models.EstadosEnvios", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoId");

                    b.ToTable("EstadosEnvio");
                });

            modelBuilder.Entity("appWebEnvio.Models.Paquetes", b =>
                {
                    b.Property<int>("PaqueteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaqueteId"));

                    b.Property<int>("EnvioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PaqueteId");

                    b.HasIndex("EnvioId");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("appWebEnvio.Models.Envios", b =>
                {
                    b.HasOne("appWebEnvio.Models.Clientes", "Clientes")
                        .WithMany("Envios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("appWebEnvio.Models.Destinatarios", "Destinatarios")
                        .WithMany("Envios")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("appWebEnvio.Models.EstadosEnvios", "EstadosEnvios")
                        .WithMany("Envios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");

                    b.Navigation("Destinatarios");

                    b.Navigation("EstadosEnvios");
                });

            modelBuilder.Entity("appWebEnvio.Models.Paquetes", b =>
                {
                    b.HasOne("appWebEnvio.Models.Envios", "Envios")
                        .WithMany("Paquetes")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envios");
                });

            modelBuilder.Entity("appWebEnvio.Models.Clientes", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("appWebEnvio.Models.Destinatarios", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("appWebEnvio.Models.Envios", b =>
                {
                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("appWebEnvio.Models.EstadosEnvios", b =>
                {
                    b.Navigation("Envios");
                });
#pragma warning restore 612, 618
        }
    }
}
